### ISSUE TITLE
Modal window with special offer

### ISSUE THREAD

**Issue by Romazes** [gaculakate/cleaning#7]
# Description
I propose to develope modal window with some special offer for our clients. When user click for btn, then he can see form which he need to full.

# Task
- [ ] Rename btn -> get a `special offer` or get a `discount`
- [ ] modal window with `form` for client
- [ ] modal need appear with animation
- [ ] background behind modal need be darken

# Additional info
![image](https://user-images.githubusercontent.com/45608740/173229801-8dcd3ef5-a011-4331-91f1-74b4f235d0d4.png)
